kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hello-world-pvc
  namespace: hello-world
  labels:
    type: local
spec:
  storageClassName: hello-world
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
