apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - name: tcp
              containerPort: 8080
          volumeMounts:
            - name: volume-mounts-on-the-pods
              mountPath: "/tmp"
      volumes:
        - name: volume-mounts-on-the-pods
          persistentVolumeClaim:
              claimName: hello-world-pvc